// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:c5bbfe00-37ff-4ea0-a65f-c821799bfb28',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'aaltoapp-hosting-mobilehub-1437599860',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1ovtf0w44smt9.cloudfront.net',
    'aws_mobile_analytics_app_id': '3d0b00aeaca8432d8b3b7ba88355af4a',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '81082db1-a4d3-443a-9b1a-ff78d0a8ff61',
    'aws_project_name': 'aalto-app-2018-11-18-21-48-01',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'aaltoapp-mobilehub-1437599860',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_lvCmsAo6v',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '2qh5m1kbgrb817sq5e8t5ct3b5',
}

export default awsmobile;
